version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rizqyfaishal/test-flip
    command: >
      bash -c "php -S 0.0.0.0:80 -t ."
    working_dir: /var/www/flip
    volumes:
      - .:/var/www/flip
    ports:
      - "$APP_PORT:80"
